export const TOP_ANIME = [
    "Shingeki no Kyojin",
  "Death Note",
  "Fullmetal Alchemist: Brotherhood",
  "One Punch Man",
  "Kimetsu no Yaiba",
  "Boku no Hero Academia",
  "Sword Art Online",
  "Hunter x Hunter (2011)",
  "Naruto",
  "Tokyo Ghoul",
  "Jujutsu Kaisen",
  "Kimi no Na wa.",
  "Shingeki no Kyojin Season 2",
  "Steins;Gate",
  "Naruto: Shippuuden",
  "Boku no Hero Academia 2nd Season",
  "One Piece",
  "Shingeki no Kyojin Season 3",
  "Koe no Katachi",
  "Shingeki no Kyojin Season 3 Part 2",
  "No Game No Life",
  "Code Geass: Hangyaku no Lelouch",
  "Re:Zero kara Hajimeru Isekai Seikatsu",
  "Shigatsu wa Kimi no Uso",
  "Boku no Hero Academia 3rd Season",
  "Toradora!",
  "Mob Psycho 100",
  "Noragami",
  "Boku dake ga Inai Machi",
  "Shingeki no Kyojin: The Final Season",
  "Akame ga Kill!",
  "Ansatsu Kyoushitsu",
  "Nanatsu no Taizai",
  "Bleach",
  "Angel Beats!",
  "Haikyuu!!",
  "Yakusoku no Neverland",
  "Kono Subarashii Sekai ni Shukufuku wo!",
  "Mirai Nikki (TV)",
  "Sword Art Online II",
  "Cowboy Bebop",
  "Ao no Exorcist",
  "Kiseijuu: Sei no Kakuritsu",
  "Sen to Chihiro no Kamikakushi",
  "Shinseiki Evangelion",
  "Violet Evergarden",
  "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
  "Chainsaw Man",
  "Dr. Stone",
  "Code Geass: Hangyaku no Lelouch R2",
  "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen",
  "Death Parade",
  "Boku no Hero Academia 4th Season",
  "Tokyo Ghoul √A",
  "Black Clover",
  "Spy x Family",
  "One Punch Man 2nd Season",
  "JoJo no Kimyou na Bouken (TV)",
  "Kill la Kill",
  "Fairy Tail",
  "Vinland Saga",
  "Darling in the FranXX",
  "Another",
  "Kimetsu no Yaiba Movie: Mugen Ressha-hen",
  "Soul Eater",
  "Tengen Toppa Gurren Lagann",
  "Tate no Yuusha no Nariagari",
  "Charlotte",
  "Overlord",
  "Psycho-Pass",
  "Shokugeki no Souma",
  "Kimetsu no Yaiba: Yuukaku-hen",
  "Mob Psycho 100 II",
  "Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.",
  "Hataraku Maou-sama!",
  "Kono Subarashii Sekai ni Shukufuku wo! 2",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
  "Tensei shitara Slime Datta Ken",
  "Horimiya",
  "Kakegurui",
  "Elfen Lied",
  "Highschool of the Dead",
  "Fate/Zero",
  "Mushoku Tensei: Isekai Ittara Honki Dasu",
  "Ansatsu Kyoushitsu 2nd Season",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
  "Haikyuu!! Second Season",
  "Fullmetal Alchemist",
  "Noragami Aragoto",
  "Shingeki no Kyojin: The Final Season Part 2",
  "Bungou Stray Dogs",
  "Made in Abyss",
  "Enen no Shouboutai",
  "High School DxD",
  "Clannad",
  "Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen",
  "Durarara!!",
  "Bakemonogatari",
  "Howl no Ugoku Shiro",
  "Hyouka",
  "Chuunibyou demo Koi ga Shitai!",
  "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
  "Owari no Seraph",
  "Sousou no Frieren",
  "Mahou Shoujo Madoka★Magica",
  "Tokyo Revengers",
  "Jujutsu Kaisen 2nd Season",
  "Mononoke Hime",
  "Dororo",
  "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders",
  "Boku no Hero Academia 5th Season",
  "Samurai Champloo",
  "Kaichou wa Maid-sama!",
  "Kobayashi-san Chi no Maid Dragon",
  "Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou",
  "Dragon Ball Z",
  "Monster",
  "Sakura-sou no Pet na Kanojo",
  "Deadman Wonderland",
  "Sono Bisque Doll wa Koi wo Suru",
  "Kuroko no Basket",
  "Tokyo Ghoul:re",
  "Clannad: After Story",
  "Zankyou no Terror",
  "Guilty Crown",
  "Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season",
  "Devilman: Crybaby",
  "Kuroshitsuji",
  "JoJo no Kimyou na Bouken Part 4: Diamond wa Kudakenai",
  "Jujutsu Kaisen 0 Movie",
  "Saiki Kusuo no Ψ-nan",
  "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders - Egypt-hen",
  "Nisekoi",
  "Kyoukai no Kanata",
  "Goblin Slayer",
  "Ouran Koukou Host Club",
  "Nanatsu no Taizai: Imashime no Fukkatsu",
  "Shokugeki no Souma: Ni no Sara",
  "Dr. Stone: Stone Wars",
  "Fate/Zero 2nd Season",
  "Log Horizon",
  "Fate/stay night: Unlimited Blade Works",
  "Tonari no Kaibutsu-kun",
  "JoJo no Kimyou na Bouken Part 5: Ougon no Kaze",
  "Tonari no Totoro",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku",
  "Gintama",
  "Mahouka Koukou no Rettousei",
  "Sword Art Online: Alicization",
  "ReLIFE",
  "Dragon Ball",
  "Golden Time",
  "Spy x Family Part 2",
  "Ore dake Level Up na Ken",
  "Overlord II",
  "K-On!",
  "Tenki no Ko",
  "Magi: The Labyrinth of Magic",
  "Mushoku Tensei: Isekai Ittara Honki Dasu Part 2",
  "Date A Live",
  "Kimi no Suizou wo Tabetai",
  "Tensei shitara Slime Datta Ken 2nd Season",
  "Black Lagoon",
  "Kimetsu no Yaiba: Katanakaji no Sato-hen",
  "Kaguya-sama wa Kokurasetai: Ultra Romantic",
  "Wotaku ni Koi wa Muzukashii",
  "Prison School",
  "Kanojo, Okarishimasu",
  "Fairy Tail (2014)",
  "Kimi ni Todoke",
  "Kami no Tou",
  "5-toubun no Hanayome",
  "Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2",
  "Haikyuu!! To the Top",
  "Cyberpunk: Edgerunners",
  "[Oshi no Ko]",
  "Shokugeki no Souma: San no Sara",
  "Youjo Senki",
  "Shinseiki Evangelion Movie: Air/Magokoro wo, Kimi ni",
  "Rakudai Kishi no Cavalry",
  "Plastic Memories",
  "Hellsing Ultimate",
  "Mahoutsukai no Yome",
  "Byousoku 5 Centimeter",
  "Ao Haru Ride",
  "Komi-san wa, Comyushou desu.",
  "Overlord III",
  "Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation",
  "Darker than Black: Kuro no Keiyakusha",
  "Fate/stay night",
  "The God of High School",
  "Yakusoku no Neverland 2nd Season",
  "Gekkan Shoujo Nozaki-kun",
  "Fumetsu no Anata e",
  "Tokyo Ghoul:re 2nd Season",
  "Nichijou",
  "Suzumiya Haruhi no Yuuutsu",
  "Kimetsu no Yaiba: Mugen Ressha-hen",
  "Masamune-kun no Revenge",
  "High School DxD New",
  "86",
  "Black Bullet",
  "Dandadan",
  "Banana Fish",
  "Baccano!",
  "Beastars",
  "Steins;Gate 0",
  "Akira",
  "Yuri!!! on Ice",
  "Bungou Stray Dogs 2nd Season",
  "No Game No Life: Zero",
  "Jigokuraku",
  "Fruits Basket 1st Season",
  "Kekkai Sensen",
  "Akatsuki no Yona",
  "Kotonoha no Niwa",
  "Boruto: Naruto Next Generations",
  "Kuroko no Basket 2nd Season",
  "Haikyuu!! To the Top Part 2",
  "Fate/stay night: Unlimited Blade Works 2nd Season",
  "Great Teacher Onizuka",
  "Enen no Shouboutai: Ni no Shou",
  "Dragon Ball Super",
  "Btooom!",
  "Tensei shitara Slime Datta Ken 2nd Season Part 2",
  "Mushishi",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka II",
  "Grand Blue",
  "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou",
  "Trinity Seven",
  "Orange",
  "Serial Experiments Lain",
  "Magi: The Kingdom of Magic",
  "FLCL",
  "Blue Lock",
  "Kokoro Connect",
  "Ijiranaide, Nagatoro-san",
  "Gate: Jieitai Kanochi nite, Kaku Tatakaeri",
  "Danshi Koukousei no Nichijou",
  "Kono Subarashii Sekai ni Shukufuku wo! Movie: Kurenai Densetsu",
  "Koutetsujou no Kabaneri",
  "Hotarubi no Mori e",
  "Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai",
  "Ookami to Koushinryou",
  "Zero no Tsukaima",
  "Ookami Kodomo no Ame to Yuki",
  "Toaru Majutsu no Index",
  "Tate no Yuusha no Nariagari Season 2",
  "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
  "Kage no Jitsuryokusha ni Naritakute!",
  "InuYasha",
  "Higurashi no Naku Koro ni",
  "Mob Psycho 100 III",
  "Boku wa Tomodachi ga Sukunai",
  "Owari no Seraph: Nagoya Kessen-hen",
  "Yamada-kun to 7-nin no Majo",
  "High School DxD BorN",
  "Vinland Saga Season 2",
  "Free!",
  "Sword Art Online: Alicization - War of Underworld",
  "Kakegurui××",
  "Toki wo Kakeru Shoujo",
  "Tonikaku Kawaii",
  "NHK ni Youkoso!",
  "Trigun",
  "Wonder Egg Priority",
  "Kuroko no Basket 3rd Season",
  "Kusuriya no Hitorigoto",
  "Sakamoto desu ga?",
  "Domestic na Kanojo",
  "Shinsekai yori",
  "Ao no Exorcist: Kyoto Fujouou-hen",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan",
  "Perfect Blue",
  "Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai",
  "Boku no Hero Academia 6th Season",
  "Arifureta Shokugyou de Sekai Saikyou",
  "Boku no Hero Academia the Movie 1: Futari no Hero",
  "Rokudenashi Majutsu Koushi to Akashic Records",
  "5-toubun no Hanayome ∬",
  "Hai to Gensou no Grimgar",
  "K",
  "Monster Musume no Iru Nichijou",
  "Kiznaiver",
  "Chuunibyou demo Koi ga Shitai! Ren",
  "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 2nd Season",
  "Isekai Maou to Shoukan Shoujo no Dorei Majutsu",
  "Nanatsu no Taizai: Kamigami no Gekirin",
  "91 Days",
  "Hellsing",
  "Mashle",
  "Bocchi the Rock!",
  "Tsurezure Children",
  "Sword Art Online Movie: Ordinal Scale",
  "Nana",
  "Nisemonogatari",
  "Shokugeki no Souma: San no Sara - Tootsuki Ressha-hen",
  "Nanatsu no Taizai: Seisen no Shirushi",
  "Ore dake Level Up na Ken Season 2: Arise from the Shadow",
  "Yofukashi no Uta",
  "Kimetsu no Yaiba: Hashira Geiko-hen",
  "Eromanga-sensei",
  "Hotaru no Haka",
  "Kenpuu Denki Berserk",
  "Ousama Ranking",
  "K-On!!",
  "Yuu☆Yuu☆Hakusho",
  "Mushoku Tensei II: Isekai Ittara Honki Dasu",
  "Great Pretender",
  "Accel World",
  "Nisekoi:",
  "Himouto! Umaru-chan",
  "Akagami no Shirayuki-hime",
  "Satsuriku no Tenshi",
  "Kuzu no Honkai",
  "3-gatsu no Lion",
  "Ore Monogatari!!",
  "D.Gray-man",
  "Shinmai Maou no Testament",
  "Rosario to Vampire",
  "Kamisama Hajimemashita",
  "Violet Evergarden Movie",
  "Blood Lad",
  "Kaijuu 8-gou",
  "Claymore",
  "Saiki Kusuo no Ψ-nan 2",
  "Ore no Imouto ga Konnani Kawaii Wake ga Nai",
  "Monogatari Series: Second Season",
  "Ergo Proxy",
  "Saenai Heroine no Sodatekata",
  "Barakamon",
  "School Days",
  "Little Witch Academia (TV)",
  "Bungou Stray Dogs 3rd Season",
  "Gakusen Toshi Asterisk",
  "Inuyashiki",
  "Blend S",
  "Koukaku Kidoutai",
  "Bleach: Sennen Kessen-hen",
  "Amagi Brilliant Park",
  "Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui!",
  "Gamers!",
  "Hataraku Saibou",
  "Lucky☆Star",
  "Suki tte Ii na yo.",
  "Shinchou Yuusha: Kono Yuusha ga Ore Tueee Kuse ni Shinchou Sugiru",
  "Psycho-Pass 2",
  "Hajime no Ippo",
  "Gintama°",
  "Sword Art Online: Alicization - War of Underworld 2nd Season",
  "Jibaku Shounen Hanako-kun",
  "Date A Live II",
  "To LOVE-Ru",
  "Pokemon",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III",
  "Dragon Ball GT",
  "Zom 100: Zombie ni Naru made ni Shitai 100 no Koto",
  "IS: Infinite Stratos",
  "Spy x Family Season 2",
  "Summertime Render",
  "Rokka no Yuusha",
  "Sword Art Online Alternative: Gun Gale Online",
  "Hige wo Soru. Soshite Joshikousei wo Hirou.",
  "Strike the Blood",
  "Shokugeki no Souma: Shin no Sara",
  "The Last: Naruto the Movie",
  "Baka to Test to Shoukanjuu",
  "Kami nomi zo Shiru Sekai",
  "Majo no Takkyuubin",
  "Sankarea",
  "Kenja no Mago",
  "Bakuman.",
  "Grisaia no Kajitsu",
  "Kore wa Zombie desu ka?",
  "Gake no Ue no Ponyo",
  "Lovely★Complex",
  "Suzumiya Haruhi no Shoushitsu",
  "Toaru Kagaku no Railgun",
  "Hunter x Hunter",
  "Log Horizon 2nd Season",
  "Shiki",
  "Kaifuku Jutsushi no Yarinaoshi",
  "Steins;Gate Movie: Fuka Ryouiki no Déjà vu",
  "86 Part 2",
  "Karakai Jouzu no Takagi-san",
  "Nagi no Asu kara",
  "Dorohedoro",
  "Vampire Knight",
  "Given",
  "Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru",
  "Overlord IV",
  "Beelzebub",
  "Boku no Hero Academia the Movie 2: Heroes:Rising",
  "SK∞",
  "Isekai wa Smartphone to Tomo ni.",
  "Tengoku Daimakyou",
  "Kawaii dake ja Nai Shikimori-san",
  "Vanitas no Karte",
  "Zetsuen no Tempest",
  "Gangsta.",
  "Ajin",
  "Evangelion Movie 1: Jo",
  "Drifters",
  "Mondaiji-tachi ga Isekai kara Kuru Sou desu yo?",
  "Darwin's Game",
  "Gintama'",
  "Kobayashi-san Chi no Maid Dragon S",
  "Paprika",
  "JoJo no Kimyou na Bouken Part 6: Stone Ocean",
  "Vivy: Fluorite Eye's Song",
  "Gate: Jieitai Kanochi nite, Kaku Tatakaeri Part 2",
  "Gosick",
  "Kiss x Sis (TV)",
  "Kuroshitsuji II",
  "Itai no wa Iya nanode Bougyoryoku ni Kyokufuri Shitai to Omoimasu.",
  "Dr. Stone: New World",
  "Netoge no Yome wa Onnanoko ja Nai to Omotta?",
  "Hajimete no Gal",
  "Higashi no Eden",
  "Tsuki ga Kirei",
  "Katanagatari",
  "Lycoris Recoil",
  "Evangelion Movie 2: Ha",
  "Ore no Kanojo to Osananajimi ga Shuraba Sugiru",
  "Absolute Duo",
  "Nekomonogatari: Kuro",
  "Natsume Yuujinchou",
  "Katekyou Hitman Reborn!",
  "Shokugeki no Souma: Gou no Sara",
  "Musaigen no Phantom World",
  "Fruits Basket 2nd Season",
  "Kizumonogatari I: Tekketsu-hen",
  "Dungeon Meshi",
  "Black Lagoon: The Second Barrage",
  "God Eater",
  "Takt Op. Destiny",
  "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2",
  "Fruits Basket",
  "Suzumiya Haruhi no Yuuutsu (2009)",
  "Mairimashita! Iruma-kun",
  "Shingeki no Kyojin: Kuinaki Sentaku",
  "Fruits Basket: The Final",
  "Ichiban Ushiro no Daimaou",
  "Boku wa Tomodachi ga Sukunai Next",
  "Fairy Tail: Final Series",
  "Shakugan no Shana",
  "Death March kara Hajimaru Isekai Kyousoukyoku",
  "Citrus",
  "High School DxD Hero",
  "Tsuki ga Michibiku Isekai Douchuu",
  "Komi-san wa, Comyushou desu. 2nd Season",
  "Mieruko-chan",
  "Kimi ni Todoke 2nd Season",
  "Hinamatsuri",
  "Sora yori mo Tooi Basho",
  "Sousei no Onmyouji",
  "Summer Wars",
  "Kono Subarashii Sekai ni Shukufuku wo! 3",
  "Megalo Box",
  "Yamada-kun to Lv999 no Koi wo Suru",
  "Yosuga no Sora",
  "Re:Creators",
  "Yuru Camp△",
  "Dandadan 2nd Season",
  "Gleipnir",
  "Aldnoah.Zero",
  "Made in Abyss: Retsujitsu no Ougonkyou",
  "Tenkuu no Shiro Laputa",
  "Made in Abyss Movie 3: Fukaki Tamashii no Reimei",
  "Kyokou Suiri",
  "Asobi Asobase",
  "Zombieland Saga",
  "Aho Girl",
  "Kage no Jitsuryokusha ni Naritakute! 2nd Season",
  "Full Metal Panic!",
  "Zero no Tsukaima: Futatsuki no Kishi",
  "Uzaki-chan wa Asobitai!",
  "Blue Period",
  "Josee to Tora to Sakana-tachi",
  "Inu x Boku SS",
  "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season",
  "Maoyuu Maou Yuusha",
  "Hataraku Maou-sama!!",
  "Usagi Drop",
  "Rurouni Kenshin: Meiji Kenkaku Romantan",
  "Mayo Chiki!",
  "Tate no Yuusha no Nariagari Season 3",
  "Ookami to Koushinryou II",
  "Seitokai Yakuindomo",
  "Higurashi no Naku Koro ni Kai",
  "Houseki no Kuni",
  "Magi: Sinbad no Bouken (TV)",
  "Fate/stay night Movie: Heaven's Feel - I. Presage Flower",
  "Tokyo Ravens",
  "[Oshi no Ko] 2nd Season",
  "Chobits",
  "Tanaka-kun wa Itsumo Kedaruge",
  "Durarara!!x2 Shou",
  "Fate/Apocrypha",
  "Kizumonogatari III: Reiketsu-hen",
  "Net-juu no Susume",
  "Hibike! Euphonium",
  "Owarimonogatari",
  "Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta...",
  "Odd Taxi",
  "Kumo desu ga, Nani ka?",
  "Tomo-chan wa Onnanoko!",
  "Mashle: Shinkakusha Kouho Senbatsu Shiken-hen",
  "Sora no Otoshimono",
  "Yuukoku no Moriarty",
  "Shingeki no Kyojin OVA",
  "Sousou no Frieren 2nd Season",
  "Ishuzoku Reviewers",
  "Ore wo Suki nano wa Omae dake ka yo",
  "Ookami Shoujo to Kuro Ouji",
  "Suzume no Tojimari",
  "Sakamoto Days",
  "Boruto: Naruto the Movie",
  "Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san",
  "Nakitai Watashi wa Neko wo Kaburu",
  "Chihayafuru",
  "Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season",
  "Beastars 2nd Season",
  "Yojouhan Shinwa Taikei",
  "Kusuriya no Hitorigoto 2nd Season",
  "Sayonara no Asa ni Yakusoku no Hana wo Kazarou",
  "Watashi ga Motete Dousunda",
  "Plunderer",
  "Tomodachi Game",
  "Evangelion Movie 3: Q",
  "Akudama Drive",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Gaiden: Sword Oratoria",
  "Dagashi Kashi",
  "Kizumonogatari II: Nekketsu-hen",
  "Cardcaptor Sakura",
  "Toaru Majutsu no Index II",
  "Gabriel DropOut",
  "Gakkougurashi!",
  "Gachiakuta",
  "Violet Evergarden Gaiden: Eien to Jidou Shuki Ningyou",
  "Shiguang Dailiren",
  "Baki",
  "Bokutachi wa Benkyou ga Dekinai",
  "Nanatsu no Taizai: Funnu no Shinpan",
  "Kekkai Sensen & Beyond",
  "Gokushufudou",
  "Boku no Hero Academia 7th Season",
  "Kanojo, Okarishimasu 2nd Season",
  "Mousou Dairinin",
  "Kaze no Stigma",
  "Steins;Gate: Oukoubakko no Poriomania",
  "Tensei shitara Slime Datta Ken 3rd Season",
  "Fugou Keiji: Balance:Unlimited",
  "Hentai Ouji to Warawanai Neko.",
  "Shirobako",
  "Love Live! School Idol Project",
  "Kamisama Hajimemashita◎",
  "Zero no Tsukaima: Princesses no Rondo",
  "World Trigger",
  "Dragon Ball Super: Broly",
  "Jujutsu Kaisen: Shimetsu Kaiyuu - Zenpen",
  "Isekai Maou to Shoukan Shoujo no Dorei Majutsu Ω",
  "Gakusen Toshi Asterisk 2nd Season",
  "No.6",
  "Tamako Market",
  "Arifureta Shokugyou de Sekai Saikyou 2nd Season",
  "Wind Breaker",
  "Koukyoushihen Eureka Seven",
  "Sono Bisque Doll wa Koi wo Suru Season 2",
  "Golden Boy",
  "Genjitsu Shugi Yuusha no Oukoku Saikenki",
  "Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su",
  "Mekakucity Actors",
  "Majo no Tabitabi",
  "Hagure Yuusha no Aesthetica",
  "Horimiya: Piece",
  "Ore no Imouto ga Konnani Kawaii Wake ga Nai.",
  "Golden Kamuy",
  "Bakemono no Ko",
  "Working!!",
  "New Game!",
  "Chainsaw Man Movie: Reze-hen",
  "Non Non Biyori",
  "Kara no Kyoukai Movie 1: Fukan Fuukei",
  "Hanamonogatari",
  "Seirei Gensouki",
  "Pandora Hearts",
  "Inou-Battle wa Nichijou-kei no Naka de",
  "Koi to Uso",
  "Tasogare Otome x Amnesia",
  "Slime Taoshite 300-nen, Shiranai Uchi ni Level Max ni Nattemashita",
  "ReLIFE: Kanketsu-hen",
  "Zero no Tsukaima F",
  "Panty & Stocking with Garterbelt",
  "Dakara Boku wa, H ga Dekinai.",
  "Shuumatsu Nani Shitemasu ka? Isogashii desu ka? Sukutte Moratte Ii desu ka?",
  "Tsukimonogatari",
  "Kono Subarashii Sekai ni Shukufuku wo!: Kono Subarashii Choker ni Shukufuku wo!",
  "Kaoru Hana wa Rin to Saku"
];