export const TOP_ANIME = [
  "Sousou no Frieren",
  "Steel Ball Run: JoJo no Kimyou na Bouken",
  "Fullmetal Alchemist: Brotherhood",
  "Chainsaw Man Movie: Reze-hen",
  "Steins;Gate",
  "Gintama: The Final",
  "Gintama°",
  "Shingeki no Kyojin Season 3 Part 2",
  "Hunter x Hunter (2011)",
  "Ginga Eiyuu Densetsu",
  "Gintama'",
  "Gintama': Enchousen",
  "One Piece Fan Letter",
  "Bleach: Sennen Kessen-hen",
  "Gintama.",
  "Kaguya-sama wa Kokurasetai: Ultra Romantic",
  "Clannad: After Story",
  "Fruits Basket: The Final",
  "Gintama",
  "Koe no Katachi",
  "Code Geass: Hangyaku no Lelouch R2",
  "Sousou no Frieren 2nd Season",
  "Kusuriya no Hitorigoto 2nd Season",
  "3-gatsu no Lion 2nd Season",
  "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare",
  "Monster",
  "Gintama. Shirogane no Tamashii-hen - Kouhan-sen",
  "Owarimonogatari 2nd Season",
  "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
  "Kusuriya no Hitorigoto",
  "Kingdom 3rd Season",
  "Shingeki no Kyojin Movie: Kanketsu-hen - The Last Attack",
  "Violet Evergarden Movie",
  "Kimi no Na wa.",
  "Vinland Saga Season 2",
  "Ashita no Joe 2",
  "Gintama. Shirogane no Tamashii-hen",
  "Re:Zero kara Hajimeru Isekai Seikatsu 4th Season",
  "Ikoku Nikki",
  "Shingeki no Kyojin: The Final Season",
  "Hajime no Ippo",
  "Kizumonogatari III: Reiketsu-hen",
  "Mob Psycho 100 II",
  "Vinland Saga",
  "Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou",
  "Sen to Chihiro no Kamikakushi",
  "Shingeki no Kyojin: The Final Season Part 2",
  "Monogatari Series: Second Season",
  "Takopii no Genzai",
  "Cowboy Bebop",
  "Bocchi the Rock!",
  "Hibike! Euphonium 3",
  "Kingdom 4th Season",
  "One Piece",
  "Tongari Boushi no Atelier",
  "86 Part 2",
  "Chi. Chikyuu no Undou ni Tsuite",
  "Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai",
  "Kingdom 5th Season",
  "Mob Psycho 100 III",
  "Mushishi Zoku Shou 2nd Season",
  "[Oshi no Ko] 3rd Season",
  "Boku no Hero Academia: Final Season",
  "Code Geass: Hangyaku no Lelouch",
  "Jujutsu Kaisen 2nd Season",
  "The First Slam Dunk",
  "Bleach: Sennen Kessen-hen - Ketsubetsu-tan",
  "Kimetsu no Yaiba: Yuukaku-hen",
  "Shiguang Dailiren",
  "Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-hen",
  "Boku no Kokoro no Yabai Yatsu 2nd Season",
  "Mushishi Zoku Shou",
  "Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen",
  "Violet Evergarden",
  "Great Teacher Onizuka",
  "Tu Bian Yingxiong X",
  "Uma Musume: Cinderella Gray Part 2",
  "Bleach: Sennen Kessen-hen - Soukoku-tan",
  "Hajime no Ippo: New Challenger",
  "Howl no Ugoku Shiro",
  "Kimetsu no Yaiba Movie 1: Mugenjou-hen - Akaza Sairai",
  "Kingdom 6th Season",
  "Mononoke Hime",
  "Jujutsu Kaisen: Shimetsu Kaiyuu - Zenpen",
  "Monogatari Series: Off & Monster Season",
  "Mushishi",
  "Uma Musume: Pretty Derby - Shin Jidai no Tobira",
  "Shigatsu wa Kimi no Uso",
  "Shingeki no Kyojin Season 3",
  "Tengen Toppa Gurren Lagann",
  "Tian Guan Cifu Er",
  "Fate/stay night Movie: Heaven's Feel - III. Spring Song",
  "Natsume Yuujinchou Shi",
  "Odd Taxi",
  "Ping Pong the Animation",
  "Cyberpunk: Edgerunners",
  "Death Note",
  "Haikyuu!! Movie: Gomisuteba no Kessen",
  "Haikyuu!! Second Season",
  "Look Back",
  "Luo Xiaohei Zhanji 2",
  "Made in Abyss",
  "Mo Dao Zu Shi: Wanjie Pian",
  "Shiguang Dailiren II",
  "Bungou Stray Dogs 5th Season",
  "Chiikawa",
  "Guimi Zhi Zhu: Xiaochou Pian",
  "Hajime no Ippo: Rising",
  "Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen",
  "Kenpuu Denki Berserk",
  "Mushoku Tensei: Isekai Ittara Honki Dasu Part 2",
  "Natsume Yuujinchou Roku",
  "Tengen Toppa Gurren Lagann Movie 2: Lagann-hen",
  "Made in Abyss Movie 3: Fukaki Tamashii no Reimei",
  "Made in Abyss: Retsujitsu no Ougonkyou",
  "Dungeon Meshi",
  "Mushishi Zoku Shou: Suzu no Shizuku",
  "Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai",
  "Suzumiya Haruhi no Shoushitsu",
  "JoJo no Kimyou na Bouken Part 5: Ougon no Kaze",
  "Natsume Yuujinchou Shichi",
  "Shin Evangelion Movie:||",
  "Uma Musume: Cinderella Gray",
  "Nana",
  "Shingeki no Kyojin",
  "Shinseiki Evangelion Movie: Air/Magokoro wo, Kimi ni",
  "Haikyuu!! To the Top Part 2",
  "Kizumonogatari II: Nekketsu-hen",
  "Natsume Yuujinchou Go",
  "Natsume Yuujinchou San",
  "Ookami Kodomo no Ame to Yuki",
  "Perfect Blue",
  "Slam Dunk",
  "Kimi no Suizou wo Tabetai",
  "Ore dake Level Up na Ken Season 2: Arise from the Shadow",
  "Shouwa Genroku Rakugo Shinjuu",
  "Steins;Gate 0",
  "Yojouhan Shinwa Taikei",
  "Fanren Xiu Xian Zhuan 4th Season",
  "Fate/Zero 2nd Season",
  "Hotaru no Haka",
  "Kaguya-sama wa Kokurasetai: Otona e no Kaidan",
  "Kimetsu no Yaiba Movie: Mugen Ressha-hen",
  "Shingeki no Kyojin Season 2",
  "Shoujo☆Kageki Revue Starlight Movie",
  "[Oshi no Ko]",
  "Fruits Basket 2nd Season",
  "Kaoru Hana wa Rin to Saku",
  "Mushishi: Hihamukage",
  "Zoku Natsume Yuujinchou",
  "Bakuman. 3rd Season",
  "Dr. Stone: Science Future Part 2",
  "Gintama Movie 1: Shinyaku Benizakura-hen",
  "Koukaku Kidoutai: Stand Alone Complex 2nd GIG",
  "Samurai Champloo",
  "Gintama. Porori-hen",
  "Given Movie 3: Umi e",
  "JoJo no Kimyou na Bouken Part 6: Stone Ocean Part 3",
  "Jujutsu Kaisen",
  "Kara no Kyoukai Movie 5: Mujun Rasen",
  "Prism Rondo",
  "[Oshi no Ko] 2nd Season",
  "Grand Blue Season 2",
  "JoJo no Kimyou na Bouken Part 4: Diamond wa Kudakenai",
  "Mahou Shoujo Madoka★Magica Movie 3: Hangyaku no Monogatari",
  "Sora yori mo Tooi Basho",
  "Tian Guan Cifu Short Films",
  "Yuru Camp△ Season 2",
  "Chou Kaguya-hime!",
  "Mob Psycho 100",
  "Xian Ni",
  "Aria the Origination",
  "One Punch Man",
  "Ousama Ranking",
  "Uchuu Kyoudai",
  "Ansatsu Kyoushitsu 2nd Season",
  "Medalist 2nd Season",
  "Nezha Zhi Mo Tong Nao Hai",
  "Nichijou",
  "Yakusoku no Neverland",
  "Chihayafuru 3",
  "Fate/stay night Movie: Heaven's Feel - II. Lost Butterfly",
  "Gintama: The Semi-Final",
  "Rainbow: Nisha Rokubou no Shichinin",
  "Summertime Render",
  "Yuu☆Yuu☆Hakusho",
  "Banana Fish",
  "Doupo Cangqiong: San Nian Zhi Yue",
  "Grand Blue",
  "Owarimonogatari",
  "Steins;Gate Movie: Fuka Ryouiki no Déjà vu",
  "Tian Guan Cifu Special",
  "Golden Kamuy 3rd Season",
  "Hunter x Hunter",
  "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders - Egypt-hen",
  "Mo Dao Zu Shi",
  "Mo Dao Zu Shi: Xian Yun Pian",
  "Pluto",
  "Zoku Owarimonogatari",
  "Chainsaw Man",
  "Haikyuu!!",
  "Kimi ni Todoke 3rd Season",
  "Mushishi Zoku Shou: Odoro no Michi",
  "Nippon Sangoku",
  "Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season",
  "Bungou Stray Dogs 4th Season",
  "Dandadan",
  "Gintama: Yorinuki Gintama-san on Theater 2D",
  "Kono Oto Tomare! Part 2",
  "Koukaku Kidoutai: Stand Alone Complex",
  "Natsume Yuujinchou Movie: Utsusemi ni Musubu",
  "Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2",
  "Saenai Heroine no Sodatekata Fine",
  "Shingeki no Kyojin: Kuinaki Sentaku",
  "Spy x Family",
  "Violet Evergarden Gaiden: Eien to Jidou Shuki Ningyou",
  "Blue Giant",
  "Dandadan 2nd Season",
  "Golden Kamuy: Saishuushou",
  "Kamisama Hajimemashita: Kako-hen",
  "Karakai Jouzu no Takagi-san Movie",
  "Kimetsu no Yaiba",
  "Mononoke",
  "Natsume Yuujinchou Roku Specials",
  "Saiki Kusuo no Ψ-nan",
  "Saiki Kusuo no Ψ-nan 2",
  "Violet Evergarden: Recollections",
  "Girls & Panzer: Saishuushou Part 4",
  "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen",
  "Kono Subarashii Sekai ni Shukufuku wo! Movie: Kurenai Densetsu",
  "Major S5",
  "Sayonara no Asa ni Yakusoku no Hana wo Kazarou",
  "Tian Guan Cifu",
  "Houseki no Kuni",
  "Made in Abyss Movie 2: Hourou Suru Tasogare",
  "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2",
  "Ashita no Joe",
  "Chihayafuru 2",
  "Cowboy Bebop: Tengoku no Tobira",
  "Doupo Cangqiong: Nian Fan",
  "Gintama°: Aizome Kaori-hen",
  "Josee to Tora to Sakana-tachi",
  "Kaze ga Tsuyoku Fuiteiru",
  "Mahou Shoujo Madoka★Magica",
  "Mahou Shoujo Madoka★Magica Movie 2: Eien no Monogatari",
  "Medalist",
  "Ramayana: The Legend of Prince Rama",
  "Vivy: Fluorite Eye's Song",
  "Wu Liuqi: Xuanwu Guo Pian",
  "Yuru Camp△ Movie",
  "3-gatsu no Lion",
  "Cross Game",
  "Haikyuu!! To the Top",
  "Jujutsu Kaisen 0 Movie",
  "Kara no Kyoukai Movie 7: Satsujin Kousatsu (Go)",
  "Karakai Jouzu no Takagi-san 3",
  "Shinseiki Evangelion",
  "Tunshi Xingkong 3rd Season",
  "Barakamon",
  "Fruits Basket: Prelude",
  "Gintama: Shiroyasha Koutan",
  "Girls Band Cry",
  "IDOLiSH7 Third Beat! Part 2",
  "Initial D First Stage",
  "K-On! Movie",
  "Kaze no Tani no Nausicaä",
  "Kizumonogatari I: Tekketsu-hen",
  "Meitantei Conan Movie 26: Kurogane no Submarine",
  "Non Non Biyori Nonstop",
  "Tunshi Xingkong 4th Season",
  "Versailles no Bara",
  "Violet Evergarden: Kitto \"Ai\" wo Shiru Hi ga Kuru no Darou",
  "86",
  "Baccano!",
  "Doraemon Movie 31: Shin Nobita to Tetsujin Heidan - Habatake Tenshi-tachi",
  "Dorohedoro Season 2",
  "Fanren Xiu Xian Zhuan: Xinghai Feichi",
  "Fate/strange Fake",
  "Fumetsu no Anata e",
  "Hibike! Euphonium 2",
  "Hyakuemu.",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan",
  "Hellsing Ultimate",
  "Kimetsu no Yaiba: Mugen Ressha-hen",
  "Kobayashi-san Chi no Maid Dragon: Samishigariya no Ryuu",
  "Kono Subarashii Sekai ni Shukufuku wo! 3",
  "Tensei shitara Slime Datta Ken 2nd Season",
  "Yofukashi no Uta Season 2",
  "Bakuman. 2nd Season",
  "Kidou Senshi Gundam: The Origin",
  "Mushoku Tensei: Isekai Ittara Honki Dasu",
  "Natsume Yuujinchou: Itsuka Yuki no Hi ni",
  "Psycho-Pass",
  "Bakemonogatari",
  "Fate/stay night: Unlimited Blade Works 2nd Season",
  "Ginga Eiyuu Densetsu: Die Neue These - Gekitotsu",
  "Ginga Eiyuu Densetsu: Die Neue These - Sakubou",
  "Hunter x Hunter: Original Video Animation",
  "Kiseijuu: Sei no Kakuritsu",
  "Major S6",
  "NHK ni Youkoso!",
  "One Outs",
  "Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season",
  "Romeo no Aoi Sora",
  "Seihantai na Kimi to Boku",
  "Uchuu Senkan Yamato 2199",
  "Uma Musume: Pretty Derby Season 2",
  "Usagi Drop",
  "Bocchi the Rock! Movie",
  "Diamond no Ace: Second Season",
  "Douluo Dalu 2nd Season",
  "Kemono no Souja Erin",
  "Natsume Yuujinchou Go Specials",
  "Sasaki to Miyano Movie: Sotsugyou-hen",
  "Boku dake ga Inai Machi",
  "Dr. Stone: New World Part 2",
  "Dr. Stone: Science Future Part 3",
  "Evangelion Movie 2: Ha",
  "Initial D Final Stage",
  "Meitantei Conan Movie 06: Baker Street no Bourei",
  "Mushen Ji",
  "Natsume Yuujinchou",
  "Ookami to Koushinryou II",
  "Shiguang Dailiren: Yingdu Pian",
  "Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.",
  "Beck",
  "Diamond no Ace: Act II",
  "Given",
  "Katanagatari",
  "Kingdom 2nd Season",
  "Kuroko no Basket 3rd Season",
  "Major: World Series",
  "Naruto: Shippuuden",
  "Redline",
  "Sakamichi no Apollon",
  "Seishun Buta Yarou wa Randoseru Girl no Yume wo Minai",
  "Steins;Gate: Oukoubakko no Poriomania",
  "Tanoshii Muumin Ikka",
  "Tensei shitara Slime Datta Ken 2nd Season Part 2",
  "Tokyo Godfathers",
  "Wu Shan Wu Xing: Xichuan Huan Zi Lin",
  "Yuukoku no Moriarty Part 2",
  "Ginga Eiyuu Densetsu: Die Neue These - Seiran 3",
  "Kino no Tabi: The Beautiful World",
  "Mononoke Movie 2: Hinezumi",
  "Rurouni Kenshin: Meiji Kenkaku Romantan",
  "Doukyuusei",
  "Gin no Saji 2nd Season",
  "Gintama: Shinyaku Benizakura-hen",
  "Haikyuu!! Movie 4: Concept no Tatakai",
  "Koukaku Kidoutai",
  "Luo Xiaohei Zhanji (Movie)",
  "Space☆Dandy 2nd Season",
  "Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero",
  "Tenki no Ko",
  "Tsubasa: Tokyo Revelations",
  "Wu Liuqi: Jiyi Suipian",
  "Yuru Camp△",
  "Dororo",
  "Dr. Stone",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka IV: Shin Shou - Yakusai-hen",
  "Fate/Zero",
  "Gyakkyou Burai Kaiji: Ultimate Survivor",
  "Hajime no Ippo: Champion Road",
  "Hajime no Ippo: Mashiba vs. Kimura",
  "Hotarubi no Mori e",
  "Hunter x Hunter: Greed Island Final",
  "Meitantei Conan: Episode One - Chiisaku Natta Meitantei",
  "Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su 2nd Season",
  "Shirobako",
  "Tenkuu no Shiro Laputa",
  "BanG Dream! It's MyGO!!!!!",
  "Dr. Stone: Science Future",
  "Gyakkyou Burai Kaiji: Hakairoku-hen",
  "IDOLiSH7 Third Beat!",
  "Kage no Jitsuryokusha ni Naritakute! 2nd Season",
  "Kuroshitsuji Movie: Book of the Atlantic",
  "Nodame Cantabile",
  "Planetes",
  "Re:Zero kara Hajimeru Isekai Seikatsu",
  "Sennen Joyuu",
  "Tonari no Totoro",
  "Golden Kamuy 2nd Season",
  "Kamisama Hajimemashita◎",
  "Kono Subarashii Sekai ni Shukufuku wo! 2",
  "Ling Long 2nd Season",
  "Majo no Takkyuubin",
  "Non Non Biyori Movie: Vacation",
  "Shinsekai yori",
  "Shoujo Kakumei Utena",
  "Shoujo Shuumatsu Ryokou",
  "Stranger: Mukou Hadan",
  "Suzume no Tojimari",
  "World Trigger 3rd Season",
  "Wu Liuqi: Anying Suming",
  "Danshi Koukousei no Nichijou",
  "Kidou Senshi Gundam: Tekketsu no Orphans 2nd Season",
  "Kono Sekai no Katasumi ni",
  "Liz to Aoi Tori",
  "Mahou Shoujo Madoka★Magica Movie 1: Hajimari no Monogatari",
  "Mimi wo Sumaseba",
  "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
  "Tamayura: Sotsugyou Shashin Part 4 - Ashita",
  "Tunshi Xingkong 2nd Season",
  "Yi Nian Yong Heng 3rd Season",
  "Youjo Senki Movie",
  "Bakemono no Ko",
  "Boku no Hero Academia 6th Season",
  "Cardcaptor Sakura Movie 2: Fuuin Sareta Card",
  "Gachiakuta",
  "Kage no Jitsuryokusha ni Naritakute!",
  "Kaguya-hime no Monogatari",
  "Kaijuu 8-gou",
  "Maison Ikkoku",
  "Major S3",
  "Nodame Cantabile Finale",
  "Stand By Me Doraemon 2",
  "Trigun",
  "Berserk: Ougon Jidai-hen III - Kourin",
  "Doupo Cangqiong 4th Season",
  "Dragon Ball Super: Broly",
  "Dragon Ball Z",
  "Fruits Basket 1st Season",
  "Haikyuu!! Movie 3: Sainou to Sense",
  "Major S1",
  "Meitantei Conan Movie 13: Shikkoku no Chaser",
  "Ookami to Koushinryou",
  "ReLIFE: Kanketsu-hen",
  "Saiki Kusuo no Ψ-nan: Kanketsu-hen",
  "Senki Zesshou Symphogear XV",
  "SKET Dance",
  "Spy x Family Season 3",
  "Tengoku Daimakyou",
  "xxxHOLiC◆Kei",
  "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 4th Season: 2-nensei-hen 1 Gakki",
  "Boku no Kokoro no Yabai Yatsu",
  "Bungou Stray Dogs 3rd Season",
  "Cang Yuan Tu 2",
  "Girls & Panzer Movie",
  "Girls & Panzer: Saishuushou Part 3",
  "InuYasha: Kanketsu-hen",
  "Kobayashi-san Chi no Maid Dragon S",
  "Kuroko no Basket 2nd Season",
  "Magi: The Kingdom of Magic",
  "Mushoku Tensei II: Isekai Ittara Honki Dasu",
  "Spy x Family Part 2",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku",
  "Yojouhan Time Machine Blues",
  "Yubisaki to Renren",
  "Yuusha-Ou GaoGaiGar Final",
  "Asobi Asobase",
  "Cardcaptor Sakura",
  "Digimon Adventure: Last Evolution Kizuna",
  "Great Pretender",
  "Hunter x Hunter: Greed Island",
  "Initial D Second Stage",
  "Jigokuraku 2nd Season",
  "Kidou Senshi Gundam: The Origin - Zenya Akai Suisei",
  "Made in Abyss Movie 1: Tabidachi no Yoake",
  "Major S4",
  "Meitantei Conan Movie 20: Junkoku no Nightmare",
  "One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari",
  "Sasaki to Miyano",
  "Vanitas no Karte Part 2",
  "Wu Liuqi: Zui Qiang Fa Xing Shi",
  "xxxHOLiC Rou",
  "Aria the Natural",
  "Ballroom e Youkoso",
  "Black Lagoon: The Second Barrage",
  "Chihayafuru",
  "Fangkai Nage Nuwu",
  "Fate/stay night: Unlimited Blade Works",
  "Ginga Eiyuu Densetsu: Die Neue These - Seiran 2",
  "Hachimitsu to Clover II",
  "Horimiya",
  "Initial D Fourth Stage",
  "Jujutsu Kaisen: Kaigyoku/Gyokusetsu",
  "K-On!!",
  "Little Busters! Refrain",
  "Major S2",
  "Meitantei Conan",
  "Natsume Yuujinchou: Ishi Okoshi to Ayashiki Raihousha",
  "Nomad: Megalo Box 2",
  "Non Non Biyori Repeat",
  "Sono Bisque Doll wa Koi wo Suru Season 2",
  "Tengen Toppa Gurren Lagann Movie 1: Gurren-hen",
  "Yoru wa Mijikashi Arukeyo Otome",
  "Yuusha-kei ni Shosu: Choubatsu Yuusha 9004-tai Keimu Kiroku",
  "Bakuman.",
  "Kamisama Hajimemashita: Kamisama, Shiawase ni Naru",
  "Kuroshitsuji: Midori no Majo-hen",
  "One Piece Movie 14: Stampede",
  "Ore dake Level Up na Ken",
  "Seishun Buta Yarou wa Santa Claus no Yume wo Minai",
  "Shen Yin Wangzuo 2nd Season",
  "Tensei shitara Slime Datta Ken 4th Season",
  "Yuukoku no Moriarty",
  "Zombieland Saga Movie: Yumeginga Paradise",
  "Akira",
  "Ao no Hako",
  "Bungou Stray Dogs 2nd Season",
  "Cang Yuan Tu",
  "Higurashi no Naku Koro ni Kai",
  "Lupin III: Cagliostro no Shiro",
  "No Game No Life: Zero",
  "Ouran Koukou Host Club",
  "Quanzhi Gaoshou Specials",
  "Yi Nian Yong Heng 2nd Season",
  "Ao Ashi",
  "Dr. Stone: Stone Wars",
  "Fate/strange Fake: Whispers of Dawn",
  "Golden Kamuy 4th Season",
  "Holo no Graffiti",
  "Kaiba",
  "Kimetsu no Yaiba: Katanakaji no Sato-hen",
  "Kono Subarashii Sekai ni Shukufuku wo! 3: Bonus Stage",
  "Kotarou wa Hitorigurashi",
  "Lupin III: Part 5",
  "Major: Message",
  "Non Non Biyori Nonstop: Bukatsu wo Ganbatta",
  "Precure All Stars Movie F",
  "Princess Tutu",
  "Black Clover",
  "Dr. Stone: New World",
  "Eiga Daisuki Pompo-san",
  "Enen no Shouboutai: San no Shou Part 2",
  "Fate/stay night Movie: Heaven's Feel - I. Presage Flower",
  "Given: Uragawa no Sonzai",
  "Hidamari Sketch: Sae Hiro Sotsugyou-hen",
  "IDOLiSH7 Second Beat!",
  "Kaze Tachinu",
  "Kyoukai no Kanata Movie 2: I'll Be Here - Mirai-hen",
  "Lycoris Recoil",
  "Mahou Shoujo Lyrical Nanoha: The Movie 2nd A's",
  "Noragami Aragoto",
  "Stand By Me Doraemon",
  "The Fable",
  "Toaru Kagaku no Railgun T",
  "Boku no Hero Academia 7th Season",
  "Death Parade",
  "Eizouken ni wa Te wo Dasu na!",
  "Ginga Eiyuu Densetsu Gaiden",
  "Horimiya: Piece",
  "Interstella5555: The 5tory of The 5ecret 5tar 5ystem",
  "Kamisama Hajimemashita",
  "Nodame Cantabile: Paris-hen",
  "Ookami to Koushinryou: Merchant Meets the Wise Wolf",
  "Seirei no Moribito",
  "Shinigami Bocchan to Kuro Maid 3rd Season",
  "Sono Bisque Doll wa Koi wo Suru",
  "Tensei shitara Slime Datta Ken",
  "Working!!! Lord of the Takanashi",
  "Blue Lock",
  "Diamond no Ace",
  "Fullmetal Alchemist",
  "Gintama': Futon ni Haitte kara Buki Nokoshi ni Kizuite Neru ni Nerenai Toki mo Aru",
  "Haikyuu!! Movie 1: Owari to Hajimari",
  "Haikyuu!! Movie 2: Shousha to Haisha",
  "Initial D Fifth Stage",
  "Katekyou Hitman Reborn!",
  "Meitantei Conan Movie 05: Tengoku e no Countdown",
  "Mirai Shounen Conan",
  "Nisemonogatari",
  "Saint Seiya: The Lost Canvas - Meiou Shinwa 2",
  "Akatsuki no Yona OVA",
  "Dr. Stone: Ryuusui",
  "Fumetsu no Anata e Season 2",
  "Gankutsuou",
  "Given Movie 1",
  "Hinamatsuri",
  "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders",
  "Kidou Senshi Gundam 00",
  "Kuragehime",
  "Meitantei Conan Movie 14: Tenkuu no Lost Ship",
  "One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna",
  "Saiki Kusuo no Ψ-nan: Ψ-shidou-hen",
  "Shokugeki no Souma",
  "Silent Witch: Chinmoku no Majo no Kakushigoto",
  "Skip to Loafer",
  "Tsurune: Tsunagari no Issha",
  "Buddy Daddies",
  "Chuunibyou demo Koi ga Shitai! Movie: Take On Me",
  "City The Animation",
  "Girls & Panzer: Saishuushou Part 2",
  "Guangyin Zhi Wai",
  "Kidou Senshi Gundam Unicorn",
  "Koukaku Kidoutai: Stand Alone Complex - Solid State Society",
  "Kyou kara Ore wa!!",
  "One Piece Film: Z",
  "Serial Experiments Lain",
  "Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su",
  "Spy x Family Movie: Code: White",
  "BanG Dream! Ave Mujica",
  "City Hunter 2",
  "Detroit Metal City",
  "Durarara!!",
  "Gin no Saji",
  "Gintama°: Umai-mono wa Atomawashi ni Suru to Yokodorisareru kara Yappari Saki ni Kue",
  "Hajime no Ippo: Boxer no Kobushi",
  "Hanada Shounen-shi",
  "Jigokuraku",
  "Kamisama Hajimemashita OVA",
  "Kono Subarashii Sekai ni Shukufuku wo!",
  "Kuroko no Basket: Saikou no Present desu",
  "Mahoutsukai no Yome: Hoshi Matsu Hito",
  "Paripi Koumei",
  "Toki wo Kakeru Shoujo",
  "Tsubasa: Shunraiki",
  "Uchouten Kazoku 2",
  "Yuanshen: Jinzhong Ge",
  "Zhan Shen: Fanchen Shenyu",
  "Azumanga Daiou The Animation",
  "Girls Band Cry Movie",
  "Given Movie 2: Hiiragi Mix",
  "Hikaru no Go",
  "Kimi wa Houkago Insomnia",
  "Kodomo no Omocha (TV)",
  "Kuroko no Basket Movie 4: Last Game",
  "Make Heroine ga Oosugiru!",
  "Persona 3 the Movie 4: Winter of Rebirth",
  "Saint Seiya: Meiou Hades Juuni Kyuu-hen",
  "Tsukimonogatari",
  "Zankyou no Terror",
  "Ansatsu Kyoushitsu",
  "Baccano! Specials",
  "Fujimoto Tatsuki 17-26",
  "Ginga Eiyuu Densetsu: Arata naru Tatakai no Overture",
  "Ginga Eiyuu Densetsu: Die Neue These - Seiran 1",
  "Gintama: Nanigoto mo Saisho ga Kanjin nanode Tashou Senobisuru Kurai ga Choudoyoi",
  "Glass no Kamen (2005)",
  "Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen 2nd Season",
  "Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen 3rd Season",
  "Hyouge Mono",
  "Jibaku Shounen Hanako-kun 2 Part 2",
  "Kanata no Astra",
  "Kidou Senshi Gundam 00 Second Season",
  "Kidou Senshi Gundam: Tekketsu no Orphans",
  "Shoushimin Series 2nd Season",
  "Skip Beat!",
  "Watashi ga Koibito ni Nareru Wake Nai jan, Muri Muri! (※Muri ja Nakatta!?) (TV Special)",
  "Diamond no Ace: Act II Second Season",
  "Ginga Eiyuu Densetsu Gaiden (1999)",
  "Gridman Universe",
  "JoJo no Kimyou na Bouken Part 6: Stone Ocean",
  "Karasu wa Aruji wo Erabanai",
  "Kidou Keisatsu Patlabor 2 the Movie",
  "Koukaku Kidoutai: Stand Alone Complex - The Laughing Man",
  "Kuroshitsuji: Book of Circus",
  "Meitantei Conan Movie 08: Ginyoku no Magician",
  "Meitantei Conan Movie 18: Ijigen no Sniper",
  "Meitantei Conan Movie 25: Halloween no Hanayome",
  "Mo Dao Zu Shi Q",
  "NieR:Automata Ver1.1a Part 2",
  "Overlord IV",
  "Shokugeki no Souma: Ni no Sara",
  "Spy x Family Season 2",
  "Yomi no Tsugai",
  "Angel Beats!",
  "Boku no Hero Academia 2nd Season",
  "Douluo Dalu II: Jueshi Tangmen",
  "Durarara!!x2 Ketsu",
  "Gintama: Dai Hanseikai",
  "Hyouka",
  "Koukyoushihen Eureka Seven",
  "Mahoutsukai no Yome",
  "Meitantei Conan Movie 03: Seikimatsu no Majutsushi",
  "Ore dake Level Up na Ken: ReAwakening",
  "Paprika",
  "Shen Yin Wangzuo",
  "World Trigger 2nd Season",
  "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 2nd Season",
  "Yowamushi Pedal: Grande Road",
  "Yuru Camp△ Season 3",
  "Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou 3 - Yakusoku",
  "Akatsuki no Yona",
  "Black Lagoon",
  "Darker than Black: Kuro no Keiyakusha",
  "Dorohedoro",
  "FLCL",
  "Ginga Nagareboshi Gin",
  "Golden Boy",
  "Gosick",
  "JoJo no Kimyou na Bouken Part 6: Stone Ocean Part 2",
  "Kuroko no Basket",
  "Kuroshitsuji: Book of Murder",
  "Meitantei Conan Movie 04: Hitomi no Naka no Ansatsusha",
  "Meitantei Conan Movie 10: Tantei-tachi no Requiem",
  "Omoide no Marnie",
  "One Piece Film: Strong World",
  "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken 2",
  "Pui Pui Molcar",
  "Sakura-sou no Pet na Kanojo",
  "Toradora!",
  "Touch",
  "Apocalypse Hotel",
  "BanG Dream! Film Live 2nd Stage",
  "BanG Dream! Movie: Episode of Roselia - II: Song I Am.",
  "Black Lagoon: Roberta's Blood Trail",
  "Dennou Coil",
  "Fate/stay night: Unlimited Blade Works Prologue",
  "Hibike! Euphonium",
  "Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen - Ryoushu no Youjo",
  "Kidou Senshi Gundam 0080: Pocket no Naka no Sensou",
  "Kill la Kill",
  "Lovely★Complex",
  "Mairimashita! Iruma-kun 4th Season",
  "No Game No Life",
  "Omae Umasou da na",
  "Quanzhi Gaoshou: Dianfeng Rongyao",
  "Shadows House 2nd Season",
  "Shijou Saikyou no Deshi Kenichi",
  "Tunshi Xingkong",
  "xxxHOLiC Shunmuki",
  "BanG Dream! 3rd Season",
  "Full Metal Panic? Fumoffu",
  "Hikaru ga Shinda Natsu",
  "Juuni Kokuki",
  "Karakai Jouzu no Takagi-san 2",
  "Kimetsu no Yaiba: Hashira Geiko-hen",
  "Mairimashita! Iruma-kun 2nd Season",
  "Mononoke Movie 1: Karakasa",
  "Naruto",
  "Slayers Next",
  "Tsuki ga Kirei",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku OVA",
  "Akane-banashi",
  "Aria the Benedizione",
  "Aria the OVA: Arietta",
  "Baby Steps 2nd Season",
  "Cheng He Titong",
  "Kara no Kyoukai Movie 3: Tsuukaku Zanryuu",
  "Kimi ni Todoke",
  "Kono Subarashii Sekai ni Shukufuku wo! 2: Kono Subarashii Geijutsu ni Shukufuku wo!",
  "Magi: The Labyrinth of Magic",
  "Meitantei Conan Movie 15: Chinmoku no Quarter",
  "Shingeki no Kyojin Movie 2: Jiyuu no Tsubasa",
  "Summer Wars",
  "Takarajima",
  "Tonikaku Kawaii: SNS",
  "Tsue to Tsurugi no Wistoria Season 2",
  "5-toubun no Hanayome ∬",
  "D.Gray-man",
  "Evangelion Movie 1: Jo",
  "Fullmetal Alchemist: Brotherhood Specials",
  "Ginga Sengoku Gunyuuden Rai",
  "Haibane Renmei",
  "Kidou Senshi Gundam: Dai 08 MS Shoutai",
  "Ruri no Houseki",
  "Saint Seiya: The Lost Canvas - Meiou Shinwa",
  "SK∞",
  "Toaru Kagaku no Railgun S",
  "Tokyo Magnitude 8.0",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
  "Yuri!!! on Ice: Yuri Plisetsky GPF in Barcelona EX - Welcome to The Madness",
  "Ao no Exorcist: Yosuga-hen",
  "Bleach",
  "Clannad",
  "Densetsu Kyojin Ideon: Hatsudou-hen",
  "ef: A Tale of Melodies.",
  "Kaichou wa Maid-sama!",
  "Kara no Kyoukai Movie: Mirai Fukuin",
  "Kindaichi Shounen no Jikenbo",
  "Saiunkoku Monogatari 2nd Season",
  "Tsumiki no Ie",
  "Vampire Hunter D (2000)",
  "Wolf's Rain OVA",
  "Zombieland Saga Revenge",
  "Aikatsu! 10th Story: Mirai e no Starway (2023)",
  "Black Clover: Mahou Tei no Ken",
  "Boku no Hero Academia 3rd Season",
  "Bungou Stray Dogs Wan!",
  "Dragon Ball",
  "Eve no Jikan",
  "Girls & Panzer: Saishuushou Part 1",
  "Hachimitsu to Clover",
  "Kami nomi zo Shiru Sekai: Megami-hen",
  "Kimi ni Todoke 2nd Season",
  "Mignon",
  "Natsu e no Tunnel, Sayonara no Deguchi",
  "Ranma ½ (2024)",
  "School Rumble Ni Gakki",
  "xxxHOLiC",
  "Aishang Ta de Liyou Extra",
  "Akagami no Shirayuki-hime 2nd Season",
  "Bishoujo Senshi Sailor Moon: Sailor Stars",
  "Code Geass: Hangyaku no Lelouch III - Oudou",
  "Crayon Shin-chan Movie 09: Arashi wo Yobu Mouretsu! Otona Teikoku no Gyakushuu",
  "Durarara!!x2 Shou",
  "Gake no Ue no Ponyo",
  "Hokuto no Ken",
  "Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen",
  "Hug tto! Precure",
  "IDOLiSH7 Vibrato",
  "Kakushigoto",
  "Kidou Senshi Gundam Thunderbolt",
  "Kidou Senshi Gundam Thunderbolt: December Sky",
  "Komi-san wa, Comyushou desu. 2nd Season",
  "Koukaku Kidoutai 2.0",
  "Koukaku Kidoutai: Stand Alone Complex 2nd GIG - Individual Eleven",
  "Kurenai no Buta",
  "Mahou Shoujo Lyrical Nanoha A's",
  "Ookiku Furikabutte: Natsu no Taikai-hen",
  "Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou-hen",
  "Shingeki no Kyojin Season 2 Movie: Kakusei no Houkou",
  "Shokugeki no Souma: San no Sara",
  "Tunshi Xingkong Movie: Xueluo Dalu",
  "Uma Musume: Pretty Derby - Road to the Top (Movie)",
  "Durarara!!x2 Ten",
  "Hidamari Sketch x Honeycomb",
  "High Score Girl: Extra Stage",
  "Les Misérables: Shoujo Cosette",
  "Macross F Movie 2: Sayonara no Tsubasa",
  "Major Movie: Yuujou no Winning Shot",
  "Ojamajo Doremi Na-i-sho",
  "ReLIFE",
  "Tennis no Oujisama: Zenkoku Taikai-hen - Final",
  "Wan Sheng Jie 2",
  "Wan Sheng Jie 3",
  "Youjo Senki",
  "Eve no Jikan (Movie)",
  "Full Moon wo Sagashite",
  "Ginga Tokkyuu Milky☆Subway",
  "Jibaku Shounen Hanako-kun 2",
  "Kizumonogatari: Koyomi Vamp",
  "Kobato.",
  "Macross: Do You Remember Love?",
  "Maoujou de Oyasumi",
  "Sword Art Online: Progressive Movie - Hoshi Naki Yoru no Aria",
  "Tamayura: Sotsugyou Shashin Part 3 - Akogare",
  "5-toubun no Hanayome∽",
  "Aria the Origination: Sono Choppiri Himitsu no Basho ni...",
  "Fate/Grand Order: Zettai Majuu Sensen Babylonia",
  "High Score Girl II",
  "IDOLiSH7 Movie: LIVE 4bit - BEYOND THE PERiOD",
  "Ie Naki Ko",
  "Kanon (2006)",
  "Kono Oto Tomare!",
  "My Melody & Kuromi",
  "Non Non Biyori",
  "Noragami",
  "Rising Impact Season 2",
  "Tekkon Kinkreet",
  "Touhai Densetsu Akagi: Yami ni Maiorita Tensai",
  "Working!!!",
  "Wotaku ni Koi wa Muzukashii OVA",
  "Yofukashi no Uta",
  "Zhu Xian 2nd Season",
  "BanG Dream! Movie: Poppin' Dream!",
  "Boku no Hero Academia the Movie 2: Heroes:Rising",
  "Clannad: Mou Hitotsu no Sekai, Tomoyo-hen",
  "Dead Dead Demons Dededede Destruction (ONA)",
  "Douluo Dalu",
  "Fate/kaleid liner Prisma☆Illya Movie: Sekka no Chikai",
  "Gochuumon wa Usagi desu ka? Bloom",
  "Heartcatch Precure!",
  "Ie Naki Ko Remy",
  "Nagi no Asu kara",
  "Nurarihyon no Mago: Sennen Makyou",
  "Osomatsu-san",
  "Sakasama no Patema",
  "Shokugeki no Souma: San no Sara - Tootsuki Ressha-hen",
  "Wan Sheng Jie",
  "xxxHOLiC Movie: Manatsu no Yoru no Yume",
  "Yi Nian Yong Heng",
  "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season",
  "Akage no Anne",
  "Benghuai: Xing Qiong Tiedao - Gelamo de Yujin",
  "Berserk: Ougon Jidai-hen - Memorial Edition",
  "Bishoujo Senshi Sailor Moon S",
  "City Hunter",
  "Eyeshield 21",
  "Fanren Xiu Xian Zhuan 2nd Season",
  "Go! Princess Precure",
  "Hanma Baki: Son of Ogre 2nd Season",
  "Hidamari Sketch x ☆☆☆",
  "Hikaru no Go: Hokuto Hai e no Michi",
  "Initial D Third Stage",
  "Kaleido Star",
  "Kidou Senshi Zeta Gundam",
  "Kimi to Boku. 2",
  "Kuuchuu Buranko",
  "Love Live! Superstar!!",
  "Love Live! The School Idol Movie",
  "Mahoutsukai no Yome Season 2 Part 2",
  "Mawaru Penguindrum",
  "Nekomonogatari: Kuro",
  "Niehime to Kemono no Ou",
  "One Piece Film: Strong World Episode 0",
  "Phantom: Requiem for the Phantom",
  "Plastic Memories",
  "Summer Ghost",
  "Wotaku ni Koi wa Muzukashii",
  "Yowamushi Pedal",
  "Yuusha-Ou GaoGaiGar",
  "Atarashii Joushi wa Do Tennen",
  "Bungou Stray Dogs: Dead Apple",
  "Code Geass: Fukkatsu no Lelouch",
  "Fanren Xiu Xian Zhuan: Xinghai Feichi Prologue",
  "Full Metal Panic! The Second Raid",
  "Hanamonogatari",
  "Kokoro Connect: Michi Random",
  "Love Live! Superstar!! 3rd Season",
  "Lupin III (2015)",
  "Meitantei Conan Movie 27: 100-man Dollar no Michishirube",
  "Oniisama e...",
  "Overlord III",
  "Romantic Killer",
  "Sakamoto Days Part 2",
  "Star☆Twinkle Precure: Hoshi no Uta ni Omoi wo Komete",
  "Tamako Love Story",
  "Usagi Drop Specials",
  "Wu Dong Qian Kun 5th Season",
  "Wu Dong Qian Kun 6th Season",
  "Yakitate!! Japan",
  "You Shou Yan 3rd Season",
  "Yuru Yuri San☆Hai!",
  "Darker than Black: Kuro no Keiyakusha Gaiden",
  "Date A Live II: Kurumi Star Festival",
  "Doraemon (1979)",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka V: Houjou no Megami-hen",
  "Ergo Proxy",
  "Gakuen Babysitters",
  "I Byeol-e Pil-yohan",
  "Karigurashi no Arrietty",
  "Kobayashi-san Chi no Maid Dragon",
  "Log Horizon",
  "Macross",
  "Meitantei Conan OVA 09: 10-nengo no Stranger",
  "New Panty & Stocking with Garterbelt",
  "One Piece: Gyojin Tou-hen",
  "Overlord",
  "Rock wa Lady no Tashinami deshite",
  "Shen Yin Wangzuo Movie: Yi Lai Ke Si Chuanqi",
  "Shirokuma Cafe",
  "Tate no Yuusha no Nariagari",
  "Trigun: Badlands Rumble",
  "Vanitas no Karte",
  "Yuri!!! on Ice",
  "Aria the Avvenire",
  "Cike Wu Liuqi",
  "Code Geass: Hangyaku no Lelouch I - Koudou",
  "Final Fantasy VII: Advent Children Complete",
  "Golden Kamuy",
  "Hanasaku Iroha",
  "Hoozuki no Reitetsu 2nd Season",
  "Kidou Senshi Gundam: Suisei no Majo Season 2",
  "Kimi no Koto ga Daidaidaidaidaisuki na 100-nin no Kanojo 2nd Season",
  "Macross F",
  "Mahou Shoujo Lyrical Nanoha: The Movie 1st",
  "Meitantei Conan Movie 02: 14-banme no Target",
  "New Initial D Movie: Legend 3 - Mugen",
  "Ore Monogatari!!",
  "Osomatsu-san Movie",
  "Promare",
  "Sakigake!! Cromartie Koukou",
  "School Rumble",
  "Shingeki no Kyojin OVA",
  "SKET Dance: Imouto no Nayami ni Nayamu Ani ni Nayamu Imouto to Sono Nakama-tachi",
  "Space☆Dandy",
  "Tamayura: Sotsugyou Shashin Part 2 - Hibiki",
  "Urusei Yatsura 2: Beautiful Dreamer",
  "Xingchen Bian 6th Season",
  "Zetsuen no Tempest",
  "Zhu Xian 3rd Season",
  "Zoku Sayonara Zetsubou Sensei",
  "Drifters",
  "Free! Eternal Summer: Kindan no All Hard!",
  "Giant Robo the Animation: Chikyuu ga Seishi Suru Hi",
  "InuYasha",
  "Jigoku Shoujo Futakomori",
  "Jormungand: Perfect Order",
  "Lupin the IIIrd: Chikemuri no Ishikawa Goemon",
  "Madogiwa no Totto-chan",
  "Megalo Box",
  "Meitantei Conan Movie 23: Konjou no Fist",
  "Musekinin Kanchou Tylor",
  "Ookiku Furikabutte",
  "Paradise Kiss",
  "Quanzhi Gaoshou 2",
  "Shijou Saikyou no Deshi Kenichi OVA",
  "Tamon-kun Ima Docchi!?",
  "Tennis no Oujisama: Zenkoku Taikai-hen",
  "Tennis no Oujisama: Zenkoku Taikai-hen - Semifinal",
  "Terra e... (TV)",
  "Ushio to Tora (TV) 2nd Season",
  "Wu Dong Qian Kun 4th Season",
  "Yagate Kimi ni Naru",
  "Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou 2 - Tamashii",
  "Yuzuki-san Chi no Yonkyoudai.",
  "Anne Shirley",
  "Berserk: Ougon Jidai-hen II - Doldrey Kouryaku",
  "Capeta",
  "Carnival Phantasm",
  "Death Billiards",
  "Free! Movie 5: The Final Stroke - Kouhen",
  "Hibike! Euphonium Movie 2: Todoketai Melody",
  "Higurashi no Naku Koro ni",
  "Hoozuki no Reitetsu 2nd Season: Sono Ni",
  "JoJo no Kimyou na Bouken (TV)",
  "K-On!"
];